#!/bin/bash

set -e

DRVNAMES="spi-s3c64xx spidev fbtft_device"

for i in ${DRVNAMES}; do
	[ `cat /etc/modules | grep $i` ] || echo $i >> /etc/modules
done

sed -i 's/^blacklist spidev/#blacklist spidev/' /etc/modprobe.d/blacklist-odroid.conf
sed -i 's/^blacklist spi_s3c64xx/#blacklist spi_s3c64xx/' /etc/modprobe.d/blacklist-odroid.conf
