#!/bin/sh

rm -f /etc/modprobe.d/odroid-cloudshell.conf

DRVNAMES="spi-s3c64xx spidev fbtft_device"

for i in ${DRVNAMES}; do
        sed -i "/$i/d" /etc/modules
done

sed -i 's/^#blacklist spidev/blacklist spidev/' /etc/modprobe.d/blacklist-odroid.conf
sed -i 's/^#blacklist spi_s3c64xx/blacklist spi_s3c64xx/' /etc/modprobe.d/blacklist-odroid.conf
